### ISSUE TITLE
Distirbute libevent 2.1.11

### ISSUE THREAD

**Issue by jjerphan** [conda-forge/libevent-feedstock#25]
### Comment:

Hi,

`libevent==2.1.10` and `libevent==2.1.12` are distributed on conda-forge, but `libevent==2.1.11` isn't (see [`libevent`'s package browser](https://anaconda.org/conda-forge/libevent/files)).

Is it possible to package this version on conda-forge? I can't as a contributor, but I am willing to become a maintainer if no current maintainer can.

Thank you.

**Comment by h-vetinari** [comment]
What is your usecase for 2.1.11? It makes barely any sense to publish that, because it would not be co-installable with a large amount of packages that have been either built for 2.1.10 or 2.1.12 (as an import example: mysql, qt, arrow) -- there can only be one version of libevent in the environment, and since the shared library is needed at runtime too, we've had to do a conda-forge-wide migration to 2.1.12 (which has already [concluded](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4453)).

You should rather help fix whatever package wants to use libevent 2.1.11 and help them work with 2.1.12.

**Comment by jjerphan** [comment]
Using libevent 2.1.10 was indeed sufficient.

Sorry for the noise.
